title: "Astroを再実装する教科書"
summary: "「もしAstroを自作するとしたら？」——この問いをガイドに、コンパイラ、アイランドアーキテクチャ、レンダラーの核心を、手を動かしながら再実装していく。フレームワークの内部構造を深く理解し、Astroの本質を掴むための、実践書。"
topics: ["astro", "islands-architecture", "compiler", "multi-framework", "zero-js"]
published: false
price: 0 # 有料の場合200〜5000
# 第1部: 思想と設計の原点
chapters:
  - 01-islands-architecture           # Islands Architectureという革新
  # 第2部: コア技術の深層
  - 02-astro-parser                  # .astroファイルパーサーの実装
  - 03-html-builder                  # シンプルなHTMLビルダーの構築
  - 04-multi-framework-renderer      # マルチフレームワークレンダラーの統合
  - 05-build-pipeline                # 完全なビルドパイプラインの実装
  - 06-selective-hydration           # 選択的ハイドレーション戦略
  - 07-content-collections           # Content Collectionsと型安全なコンテンツ管理
  # 第3部: 実践と応用、そして未来
  - 08-performance-optimization      # パフォーマンス計測と最適化
  - 09-developer-experience          # 開発体験（DX）の向上
  - 10-ecosystem-extensions          # エコシステムと未来への拡張